// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ServerApp.Models;

#nullable disable

namespace ServerApp.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.0");

            modelBuilder.Entity("ServerApp.Models.Item", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Semester")
                        .HasColumnType("INTEGER");

                    b.Property<int>("UserId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Items", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "C# базовий курс",
                            Name = "Програмування 1",
                            Semester = 1,
                            UserId = 1
                        },
                        new
                        {
                            Id = 2,
                            Description = "SQL та БД",
                            Name = "Бази даних",
                            Semester = 3,
                            UserId = 1
                        },
                        new
                        {
                            Id = 3,
                            Description = "Основи мереж",
                            Name = "Комп'ютерні мережі",
                            Semester = 4,
                            UserId = 2
                        });
                });

            modelBuilder.Entity("ServerApp.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Users", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Email = "ivan.petrov@uni.edu",
                            Name = "Іван Петров",
                            PasswordHash = "HASH1"
                        },
                        new
                        {
                            Id = 2,
                            Email = "olena.ivanenko@uni.edu",
                            Name = "Олена Іваненко",
                            PasswordHash = "HASH2"
                        });
                });

            modelBuilder.Entity("ServerApp.Models.UserAction", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ActionDetails")
                        .HasColumnType("TEXT");

                    b.Property<string>("ActionType")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("ItemId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("UserId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ItemId");

                    b.HasIndex("UserId");

                    b.ToTable("Actions", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ActionDetails = "Створити курс",
                            ActionType = "Create",
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            ItemId = 1,
                            Status = "Approved",
                            UserId = 1
                        },
                        new
                        {
                            Id = 2,
                            ActionDetails = "Обʼєднати з іншим",
                            ActionType = "Delete",
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            ItemId = 2,
                            Status = "Pending",
                            UserId = 1
                        },
                        new
                        {
                            Id = 3,
                            ActionDetails = "Новий курс з мереж",
                            ActionType = "Create",
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            ItemId = 3,
                            Status = "Rejected",
                            UserId = 2
                        });
                });

            modelBuilder.Entity("ServerApp.Models.Item", b =>
                {
                    b.HasOne("ServerApp.Models.User", "User")
                        .WithMany("Items")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("ServerApp.Models.UserAction", b =>
                {
                    b.HasOne("ServerApp.Models.Item", "Item")
                        .WithMany("Actions")
                        .HasForeignKey("ItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ServerApp.Models.User", "User")
                        .WithMany("Actions")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Item");

                    b.Navigation("User");
                });

            modelBuilder.Entity("ServerApp.Models.Item", b =>
                {
                    b.Navigation("Actions");
                });

            modelBuilder.Entity("ServerApp.Models.User", b =>
                {
                    b.Navigation("Actions");

                    b.Navigation("Items");
                });
#pragma warning restore 612, 618
        }
    }
}
